### ISSUE TITLE
Will you provide pretrained models?

### ISSUE THREAD

**Issue by Guptajakala** [lppllppl920/DenseDescriptorLearning-Pytorch#1]
Hi, thanks for the nice work. I wanted to try it out directly on another research task. Do you plan to release the pretrained models?

**Comment by lppllppl920** [comment]
Hi Guptajakala, because the pre-trained models are trained on an in-house sinus endoscopy dataset, I don't think it will be very helpful for your own task. But if you need it, I can still share it with you.

**Comment by resindraburiza** [comment]
Hi @lppllppl920 ,

sorry for hijacking this closed thread. Would you mind sharing the pre-trained model with me too? I believe it will be so much help to me.

Best,
resindra

**Comment by davidz123** [comment]
Hi， Could you share your trained model with me for priamry test，I really appreciate it.

**Comment by davidz123** [comment]
Hi @lppllppl920 ， Could you share your trained model with me for priamry test，I really appreciate it.

**Comment by fromWRF** [comment]
Hi @lppllppl920 , Could you also share your trained model with me? I believe it will be helpful.

Best wishes,
wrf
