### ISSUE TITLE
About feature matches location for training and validation

### ISSUE THREAD

**Issue by resindraburiza** [lppllppl920/DenseDescriptorLearning-Pytorch#2]
Hi.

Thank you very much for sharing your work. 
I am planning to try your code on my own dataset but unfortunately, I cannot understand how you get the feature matches locations.

This is how I understand your code:
1. you get the extrinsic parameters and (undistorted) intrinsic parameters from each view
2. make projection matrix based on those two for each view
3. project 3D point to each view based on the projection matrix
But, this projection should be in a space of undistorted image, shouldn't it? But I cannot find the part of your code that does image undistortion or move the projected pixel location from undistorted to distorted space. Since in the training you are still using distorted images, wouldn't the feature locations are wrong? Is there something that I missed?

thank you very much!

Best,
resindra

**Comment by lppllppl920** [comment]
Hi @resindraburiza, 

The images in the shared dataset have already been undistorted. You are correct that we did not put the distortion related code on this Github repo. Any standard way of undistorting the camera will work. We did share a python script in this repo to generate point-video overlay to help you verify whether or not the camera distortion has been fixed.

**Comment by resindraburiza** [comment]
Hi,

Thank you for your answer. I thought that the image is still distorted. 

Best,
resindra
