### ISSUE TITLE
Dense feature learning

### ISSUE THREAD

**Issue by sdpscnc** [lppllppl920/DenseDescriptorLearning-Pytorch#4]
Hello, thank you for your excellent work. I used your code to learn dense features on my data set. I also did the same for your data set. I am not sure if the learning result is correct. Can you provide your trained model? I want to test it. thanks again.

**Comment by crystaljiajia** [comment]
Dear all,

Thanks for sharing your code!
Could you share your trained model with me?
I really appreciate it.

Best regards

**Comment by lppllppl920** [comment]
Sorry for the late reply. Because our dataset for training the model is sensitive and therefore we cannot share our model to avoid the risk of the potential training data leak.
